CREATE TABLE person (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `gender` VARCHAR(1) DEFAULT "N",
  `birthDate` DATE NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT ck_person CHECK (`gender` IN ("F", "M", "N")),
  CONSTRAINT pk_person PRIMARY KEY (`id`)
);

CREATE TABLE phone (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `number` VARCHAR(20) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_phone_person FOREIGN KEY (`person_id`) REFERENCES person(`id`),
  CONSTRAINT pk_phone PRIMARY KEY (`id`)
);

CREATE TABLE email (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_email_person FOREIGN KEY (`person_id`) REFERENCES person(`id`),
  CONSTRAINT pk_email PRIMARY KEY (`id`)
);

CREATE TABLE address (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `number` VARCHAR(10) NOT NULL,
  `complement` VARCHAR(255),
  `neighborhood` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zipCode` VARCHAR(8) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_address_person FOREIGN KEY (`person_id`) REFERENCES person(`id`),
  CONSTRAINT pk_address PRIMARY KEY (`id`)
);

CREATE TABLE user (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `online` BOOLEAN DEFAULT TRUE NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_person FOREIGN KEY (id) REFERENCES person(id),
  CONSTRAINT pk_user PRIMARY KEY (`id`)
);

CREATE TABLE presence (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `confirmed` BOOLEAN DEFAULT TRUE NOT NULL,
  `attended` BOOLEAN DEFAULT TRUE NOT NULL,
  `paid` VARCHAR(255) NOT NULL,
  `notes` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_presence_person FOREIGN KEY (`person_id`) REFERENCES person(`id`),
  CONSTRAINT pk_presence PRIMARY KEY (`id`)
);
